### ISSUE TITLE
再ant design pro里面scss没法解析

### ISSUE THREAD

**Issue by jarrywen** [gaoli/GGEditor#103]
再ant design pro里面scss没法解析
需要增加什么配置，才能够使用scss

**Comment by gaoli** [comment]
https://github.com/gaoli/GGEditor/blob/master/tools/webpack.config.base.js#L13

试试：）

**Comment by jarrywen** [comment]
ant design pro是用roadhog的.webpackrc.js取代webpack.config.base.js。

看[webpackrc的文档](https://github.com/sorrycc/roadhog/blob/master/README_zh-cn.md#entry)里只有sass的配置，没有scss。

现在主要是不懂怎样把scss的配置移植到.webpackrc.js，或者只能把scss改成less？

.webpackrc.js内容如下：
```
const path = require('path');
export default {
  entry: 'src/index.js',
  extraBabelPlugins: [
    ['import', { libraryName: 'antd', libraryDirectory: 'es', style: true }],
  ],
  env: {
    development: {
      extraBabelPlugins: ['dva-hmr'],
    },
  },
  alias: {
    components: path.resolve(__dirname, 'src/components/'),
  },
  ignoreMomentLocale: true,
  theme: './src/theme.js',
  html: {
    template: './src/index.ejs',
  },
  disableDynamicImport: true,
  publicPath: '/',
  hash: true,
};
```

> https://github.com/gaoli/GGEditor/blob/master/tools/webpack.config.base.js#L13
> 
> 试试：）

**Comment by gaoli** [comment]
@jarrywen 

直接使用 sass 的配置即可：）

**Comment by sy13277072001** [comment]
> ant design pro是用roadhog的.webpackrc.js取代webpack.config.base.js。
> 
> 看[webpackrc的文档](https://github.com/sorrycc/roadhog/blob/master/README_zh-cn.md#entry)里只有sass的配置，没有scss。
> 
> 现在主要是不懂怎样把scss的配置移植到.webpackrc.js，或者只能把scss改成less？
> 
> .webpackrc.js内容如下：
> 
> ```
> const path = require('path');
> export default {
>   entry: 'src/index.js',
>   extraBabelPlugins: [
>     ['import', { libraryName: 'antd', libraryDirectory: 'es', style: true }],
>   ],
>   env: {
>     development: {
>       extraBabelPlugins: ['dva-hmr'],
>     },
>   },
>   alias: {
>     components: path.resolve(__dirname, 'src/components/'),
>   },
>   ignoreMomentLocale: true,
>   theme: './src/theme.js',
>   html: {
>     template: './src/index.ejs',
>   },
>   disableDynamicImport: true,
>   publicPath: '/',
>   hash: true,
> };
> ```
> > https://github.com/gaoli/GGEditor/blob/master/tools/webpack.config.base.js#L13
> > 试试：）

你的问题解决了么，我也是这个问题呢

**Comment by jarrywen** [comment]
> > @jarrywen
> > 直接使用 sass 的配置即可：）
> 
> 你好，我也是上面的问题，用的ant design pro 搭建的项目，没有webpack.config.base.js文件，只有webpackrc.js，不知道要怎么配置才能支持.scss文件，而且驼峰形式的样式名，在scss文件中用的是小写的-来替代的，不知道要怎么配置，ant design pro中的css文件是.less的。

理论上只要在.webpackrc.js配置上"sass": false就ok了，我稍微试了下还是不行。
后面ant design pro新版本用umi了，ggeditor的基础g6 editor也没开源，所以就没弄了。

**Comment by gaoli** [comment]
@jarrywen @sy13277072001 

1.5.0 版本已经使用 Less 预处理 CSS  :)
