### ISSUE TITLE
元素面板栏是否支持自定义呢？

### ISSUE THREAD

**Issue by z784324922** [gaoli/GGEditor#104]
看了一下流程图的代码，在ItemPanel下的item通过shape选取特定的图形。我想引入自己的component，每个component都是一个G2的图形，然后实现拖拽显示在画布上。

**Comment by z784324922** [comment]
我看了下，自定义注册一个node类型，通过draw绘制一些简单的图形倒没啥问题。但我们目前使用的图形都是bizcharts的组件，比如折线图，矩形图。有没有什么方法，可以直接引入这些组件。 主要是为了实现图形在画布上面拖拽显示，并支持覆盖。

**Comment by tdida** [comment]
@gaoli 使用RegisterNode 自定义node，在itemPane里拖动出来无效，在flow初始化data里自定义node可以显示

**Comment by gaoli** [comment]
@z784324922 不好意思，现在 `G6-Editor` 只支持这种注册的方式呢：）
