### ISSUE TITLE
怎么禁止键盘的删除键  delete  Flow里的元素呢？

### ISSUE THREAD

**Issue by ouaisheinie** [gaoli/GGEditor#106]
好下井onKeyDown来设置  没办法  还是会被删除

**Comment by ouaisheinie** [comment]
好像没有思绪   需要在源码里面看吗

**Comment by gaoli** [comment]
@ouaisheinie 

```jsx
<RegisterCommand name="delete" config={{ shortcutCodes: [] }} extend="delete" />
```

尝试复写 `delete` 命令，将 `shortcutCodes` 属性设置为 `[]`

**Comment by ouaisheinie** [comment]
ok

**Comment by JoMartinezZhu** [comment]
> @ouaisheinie
> 
> ```js-jsx
> <RegisterCommand name="delete" config={{ shortcutCodes: [] }} extend="delete" />
> ```
> 
> 尝试复写 `delete` 命令，将 `shortcutCodes` 属性设置为 `[]`

这些 API 上都没有，我要是还有其他需求，不知该如何 快速的找到相应的文档？

**Comment by MrHuang123** [comment]
试了一下好像还是不行
