### ISSUE TITLE
有木有什么方法阻止连接线到空白处！

### ISSUE THREAD

**Issue by zsl1549** [gaoli/GGEditor#110]
## 你所期望的 API 是怎样的
 
![image](https://user-images.githubusercontent.com/32888522/49139072-d192c400-f32b-11e8-87bb-41be36ded834.png)

**Comment by gaoli** [comment]
试试 `noEndEdge` 参数

https://www.yuque.com/antv/g6-editor/flow-api#5l1pzl

**Comment by zsl1549** [comment]
谢谢作者,解决了。    请问作者 设置自定义节点，registerNode 有木有一些案例，api文档不太全。

**Comment by gaoli** [comment]
@zsl1549 

参考这个：https://github.com/gaoli/GGEditor/issues/76#issuecomment-428101146

**Comment by zsl1549** [comment]
谢谢。 @gaoli
