### ISSUE TITLE
自定义节点图形，求告知谢谢。

### ISSUE THREAD

**Issue by zsl1549** [gaoli/GGEditor#113]
![image](https://user-images.githubusercontent.com/32888522/49157742-7c6ea680-f35b-11e8-9f54-3865f59db27d.png)
定义个别的图形不可以，出来的永远是矩形。

**Comment by gaoli** [comment]
@zsl1549 

请参照 [Flow](https://codesandbox.io/s/m2v96ok1p) 提供重现链接

**Comment by zsl1549** [comment]
| flow-circle | 起止节点 | ![起止节点](https://gw.alipayobjects.com/zos/rmsportal/ZnPxbVjKYADMYxkTQXRi.svg) | Flow |
| flow-rect | 常规节点 | ![起止节点](https://gw.alipayobjects.com/zos/rmsportal/wHcJakkCXDrUUlNkNzSy.svg) | Flow |
| flow-rhombus | 分叉节点 | ![分叉节点](https://gw.alipayobjects.com/zos/rmsportal/SnWIktArriZRWdGCnGfK.svg) | Flow |
| flow-capsule | 模型节点 | ![模型节点](https://gw.alipayobjects.com/zos/rmsportal/rQMUhHHSqwYsPwjXxcfP.svg) | Flow |

我想自定义 一些节点  ，换个形状，求指导。。

**Comment by zsl1549** [comment]
![image](https://user-images.githubusercontent.com/32888522/49193372-def68f80-f3b9-11e8-942e-3f297744e2b0.png)
引入本地的 svg地址 怎么写？

**Comment by tdida** [comment]
可以看下这个 https://www.yuque.com/antv/g6/worldcup-tree

**Comment by tdida** [comment]
> ![image](https://user-images.githubusercontent.com/32888522/49193372-def68f80-f3b9-11e8-942e-3f297744e2b0.png)
> 引入本地的 svg地址 怎么写？

把 svg import 进来

`import defaultSvg from '@/assets/svg/default.svg';`

**Comment by zsl1549** [comment]
![image](https://user-images.githubusercontent.com/32888522/49193921-03536b80-f3bc-11e8-8db0-00cd36ae14c6.png)
大哥写法不对吗?

**Comment by tdida** [comment]
什么意思，引入不就可以直接使用了吗

**Comment by zsl1549** [comment]
![image](https://user-images.githubusercontent.com/32888522/49194044-82e13a80-f3bc-11e8-8e1e-a17f5088ed56.png)
![image](https://user-images.githubusercontent.com/32888522/49194087-b02de880-f3bc-11e8-856b-b23e5134ee91.png)

**Comment by tdida** [comment]
webpack 有做引入svg处理吗

**Comment by zsl1549** [comment]
下载的地址https://github.com/gaoli/GGEditor    ，里面应该没有吧？需要做什么配置吗，看例子都是 线上的svg地址 ，本地的就没有？ @tdida

**Comment by gaoli** [comment]
@zsl1549 请提供在线 DEMO，方便我们帮助排查：）

**Comment by zsl1549** [comment]
@gaoli

**Comment by gaoli** [comment]
@zsl1549 使用 [CodeSandbox](https://codesandbox.io/s/m2v96ok1p)

**Comment by zsl1549** [comment]
https://codesandbox.io/s/8n08k17wp8 @gaoli  大哥看看是什么问题

**Comment by zsl1549** [comment]
@gaoli 谢谢大哥指教， 
![image](https://user-images.githubusercontent.com/32888522/49909792-47199b00-febb-11e8-85c2-b225925ed7f1.png)
我只想保留图片和锚点，不想要圆形。
求指教，谢谢。https://codesandbox.io/s/8n08k17wp8

**Comment by gaoli** [comment]
@zsl1549 去掉一些属性即可

```jsx
const keyShape = group.addShape("rect", {
  attrs: {
    x,
    y,
    width,
    height,
  }
});
```

**Comment by zsl1549** [comment]
@gaoli 锚点没了
![image](https://user-images.githubusercontent.com/32888522/49912169-315ca380-fec4-11e8-82a8-fa61577e810c.png)
https://codesandbox.io/s/8n08k17wp8

**Comment by gaoli** [comment]
@zsl1549 

`rect` 图形设置好宽高，把填充与边框色设置成与背景颜色一样即可：）

**Comment by zsl1549** [comment]
![image](https://user-images.githubusercontent.com/32888522/49919185-b1910200-fee0-11e8-9e6e-0ae93763ecc2.png)
![image](https://user-images.githubusercontent.com/32888522/49919251-eac97200-fee0-11e8-9bf4-6b7d6d54d04f.png)
本地引入svg 就报错。。。。为什么呀！555555 @gaoli

**Comment by gaoli** [comment]
@zsl1549 引入 SVG 文件报错是打包配置的问题，可以参考 [svg-inline-loader](https://github.com/webpack-contrib/svg-inline-loader)

**Comment by zsl1549** [comment]
ok
