### ISSUE TITLE
本地资源img访问不到

### ISSUE THREAD

**Issue by zsl1549** [gaoli/GGEditor#114]
![image](https://user-images.githubusercontent.com/32888522/49198628-fe4be780-f3ce-11e8-83d4-ebe3668b1fbe.png)
![image](https://user-images.githubusercontent.com/32888522/49198653-17549880-f3cf-11e8-9dda-1f5e97e320b5.png)

**Comment by gaoli** [comment]
包含 `src` 属性时会增加一个 `img` 标签，打包相关问题请查看 [webpack](https://webpack.js.org/configuration/dev-server/#devserver) 文档：）

https://github.com/gaoli/GGEditor/blob/master/src/components/ItemPanel/Item.js#L37

**Comment by zsl1549** [comment]
路径问题。。。  @gaoli 请教我要做一个自定义 节点 看下面图片。怎么实现，有什么好的办法吗？
![image](https://user-images.githubusercontent.com/32888522/49207834-0b79ce00-f3f1-11e8-83bd-0122dbdddff3.png)

**Comment by gaoli** [comment]
@zsl1549 

G6 底层使用的是 [G](https://github.com/antvis/g)，如果想要简单实现就直接绘制一张[图片](https://github.com/antvis/g#shapeimage) :)

**Comment by zsl1549** [comment]
import G6 from '@antv/g6'; 下载完G6引入报错为什么啊?懵逼了，不是基于G6开发吗。。求告知！谢谢
![image](https://user-images.githubusercontent.com/32888522/49215383-a2e81c80-f403-11e8-887e-84c65ca39801.png)

**Comment by gaoli** [comment]
@zsl1549 

上述的报错信息显示是在打包过程中缺少插件，请尝试 `npm install`

还有一个问题是为什么需要单独引入 `G6` ?

**Comment by zsl1549** [comment]
因为要画图
![image](https://user-images.githubusercontent.com/32888522/49842253-be84f700-fdf5-11e8-82da-565703545e53.png)
怎么快速的 把自定义节点 换成 这样的形状 ，而不是 圆形 长方形 。

**Comment by zsl1549** [comment]
@gaoli 
求指点

**Comment by gaoli** [comment]
@zsl1549 不要重复提问，新问题提新的 issue，谢谢：）
