### ISSUE TITLE
G6模型流程图在GGEditor中如何实现？

### ISSUE THREAD

**Issue by yinbanghui** [gaoli/GGEditor#115]
想要实现类似G6模型流程图功能，如图所示：

![image](https://user-images.githubusercontent.com/10389726/49208654-54cb1d00-f3f3-11e8-9eb4-994fa1b25b8f.png)

GGEditor介绍中有这个demo，但是源码中未找到这个demo源码，能找到这个
![image](https://user-images.githubusercontent.com/10389726/49208749-8e038d00-f3f3-11e8-98f4-b6ba2c054f73.png)
想知道前者是如何实现的？在G6源码中也未找到源码

**Comment by yinbanghui** [comment]
非常感谢！
请问下，这里如何修改配置呢？
```
  <ItemPanel className="item-panel">
        <Card bordered={false}>
          <Item
            type="node"
            size="72*72"
            shape="flow-circle"
            model={{
              color: '#FA8C16',
              label: '起止节点',
            }}
            src="https://gw.alipayobjects.com/zos/rmsportal/ZnPxbVjKYADMYxkTQXRi.svg"
          />
```

**Comment by gaoli** [comment]
@yinbanghui 请具体描述你的需求，谢谢

**Comment by zsl1549** [comment]
@yinbanghui 咋们的需求好像一样，要自定义节点。 不好自定义节点、。。。。

**Comment by yinbanghui** [comment]
具体的需求是：
将这种形式
![image](https://user-images.githubusercontent.com/10389726/49261090-943d4c00-f47b-11e8-9499-558e6689ed45.png)
转换为这种形式
![image](https://user-images.githubusercontent.com/10389726/49261120-b59e3800-f47b-11e8-9eee-e7a7d4ee943c.png)
节点已经参考 #37的方法注册节点
```
                <RegisterNode
                      name="model-card"
                      config={{
                        draw(item) {
                          const group = item.getGraphicGroup();
                          const model = item.getModel();
                          const width = 184;
                          const height = 40;
                          const x = -width / 2;
                          const y = -height / 2;
                          const borderRadius = 4;
                          const keyShape = group.addShape('rect', {
                            attrs: {
                              x,
                              y,
                              width,
                              height,
                              radius: borderRadius,
                              fill: 'white',
                              stroke: '#CED4D9',
                            },
                          });
```
现在的问题是，目前内置节点配置方法为：
```
<ItemPanel className="item-panel">
        <Card bordered={false}>
          <Item
            type="node"
            size="72*72"
            shape="flow-circle"
            model={{
              color: '#FA8C16',
              label: '起止节点',
            }}
            src="https://gw.alipayobjects.com/zos/rmsportal/ZnPxbVjKYADMYxkTQXRi.svg"
          />
```
如何通过修改这个配置能引入上午自定义的节点，谢谢啦！！！

**Comment by yinbanghui** [comment]
@zsl1549 自定义节点配置好了吗？

**Comment by zsl1549** [comment]
没有 api也不全G6 我引入还报错 唉。。。。

**Comment by sy13277072001** [comment]
> 具体的需求是：
> 将这种形式
> ![image](https://user-images.githubusercontent.com/10389726/49261090-943d4c00-f47b-11e8-9499-558e6689ed45.png)
> 转换为这种形式
> ![image](https://user-images.githubusercontent.com/10389726/49261120-b59e3800-f47b-11e8-9eee-e7a7d4ee943c.png)
> 节点已经参考 #37的方法注册节点
> 
> ```
>                 <RegisterNode
>                       name="model-card"
>                       config={{
>                         draw(item) {
>                           const group = item.getGraphicGroup();
>                           const model = item.getModel();
>                           const width = 184;
>                           const height = 40;
>                           const x = -width / 2;
>                           const y = -height / 2;
>                           const borderRadius = 4;
>                           const keyShape = group.addShape('rect', {
>                             attrs: {
>                               x,
>                               y,
>                               width,
>                               height,
>                               radius: borderRadius,
>                               fill: 'white',
>                               stroke: '#CED4D9',
>                             },
>                           });
> ```
> 现在的问题是，目前内置节点配置方法为：
> 
> ```
> <ItemPanel className="item-panel">
>         <Card bordered={false}>
>           <Item
>             type="node"
>             size="72*72"
>             shape="flow-circle"
>             model={{
>               color: '#FA8C16',
>               label: '起止节点',
>             }}
>             src="https://gw.alipayobjects.com/zos/rmsportal/ZnPxbVjKYADMYxkTQXRi.svg"
>           />
> ```
> 如何通过修改这个配置能引入上午自定义的节点，谢谢啦！！！

 自定义节点要怎么引入呢，你的问题解决了么，自定义节点代码要放在哪里呢？

**Comment by Jexecellent** [comment]
各位大佬还在用gg-editor吗
