### ISSUE TITLE
withPropsAPI 图形编辑之后save信息

### ISSUE THREAD

**Issue by yinbanghui** [gaoli/GGEditor#116]
## 这个功能解决了什么问题
![image](https://user-images.githubusercontent.com/10389726/49359500-63764480-f711-11e8-8956-968eaeed23a8.png)
## 你所期望的 API 是怎样的
希望图形编辑变成之后能够保存

**Comment by gaoli** [comment]
@yinbanghui 请提供下在线的 DEMO，谢谢：）

**Comment by zsl1549** [comment]
import React from 'react';
import { Tooltip, Divider,Button } from 'antd';
import { Toolbar, Command } from '@src';
import styles from './index.scss';
import iconfont from '../../theme/iconfont.scss';
import { Flow, withPropsAPI } from '@src';

class FlowToolbar extends React.Component {
  constructor(props){
    super(props);
}
  saveFlow = () =>{
    console.log(this.props.propsAPI.save());
}

  render() {
    return (
      <Toolbar className={styles.toolbar}>
        <Command name="undo">
          <Tooltip title="撤销" placement="bottom" overlayClassName={styles.tooltip}>
            <i className={`${iconfont.iconfont} ${iconfont.iconUndo}`} />
          </Tooltip>
        </Command>
        <Command name="redo">
          <Tooltip title="重做" placement="bottom" overlayClassName={styles.tooltip}>
            <i className={`${iconfont.iconfont} ${iconfont.iconRedo}`} />
          </Tooltip>
        </Command>
        <Divider type="vertical" />
        <Command name="copy">
          <Tooltip title="复制" placement="bottom" overlayClassName={styles.tooltip}>
            <i className={`${iconfont.iconfont} ${iconfont.iconCopyO}`} />
          </Tooltip>
        </Command>
        <Command name="paste">
          <Tooltip title="粘贴" placement="bottom" overlayClassName={styles.tooltip}>
            <i className={`${iconfont.iconfont} ${iconfont.iconPasterO}`} />
          </Tooltip>
        </Command>
        <Command name="delete">
          <Tooltip title="删除" placement="bottom" overlayClassName={styles.tooltip}>
            <i className={`${iconfont.iconfont} ${iconfont.iconDeleteO}`} />
          </Tooltip>
        </Command>
        <Divider type="vertical" />
        <Command name="zoomIn">
          <Tooltip title="放大" placement="bottom" overlayClassName={styles.tooltip}>
            <i className={`${iconfont.iconfont} ${iconfont.iconZoomInO}`} />
          </Tooltip>
        </Command>
        <Command name="zoomOut">
          <Tooltip title="缩小" placement="bottom" overlayClassName={styles.tooltip}>
            <i className={`${iconfont.iconfont} ${iconfont.iconZoomOutO}`} />
          </Tooltip>
        </Command>
        <Command name="autoZoom">
          <Tooltip title="适应画布" placement="bottom" overlayClassName={styles.tooltip}>
            <i className={`${iconfont.iconfont} ${iconfont.iconFit}`} />
          </Tooltip>
        </Command>
        <Command name="resetZoom">
          <Tooltip title="实际尺寸" placement="bottom" overlayClassName={styles.tooltip}>
            <i className={`${iconfont.iconfont} ${iconfont.iconActualSizeO}`} />
          </Tooltip>
        </Command>
        <Divider type="vertical" />
        <Command name="toBack">
          <Tooltip title="层级后置" placement="bottom" overlayClassName={styles.tooltip}>
            <i className={`${iconfont.iconfont} ${iconfont.iconToBack}`} />
          </Tooltip>
        </Command>
        <Command name="toFront">
          <Tooltip title="层级前置" placement="bottom" overlayClassName={styles.tooltip}>
            <i className={`${iconfont.iconfont} ${iconfont.iconToFront}`} />
          </Tooltip>
        </Command>
        <Divider type="vertical" />
        <Command name="multiSelect">
          <Tooltip title="多选" placement="bottom" overlayClassName={styles.tooltip}>
            <i className={`${iconfont.iconfont} ${iconfont.iconSelect}`} />
          </Tooltip>
        </Command>
        <Command name="addGroup">
          <Tooltip title="成组" placement="bottom" overlayClassName={styles.tooltip}>
            <i className={`${iconfont.iconfont} ${iconfont.iconGroup}`} />
          </Tooltip>
        </Command>
        <Command name="unGroup">
          <Tooltip title="解组" placement="bottom" overlayClassName={styles.tooltip}>
            <i className={`${iconfont.iconfont} ${iconfont.iconUngroup}`} />
          </Tooltip>
        </Command>
        <div>
        <Button onClick={()=>{this.saveFlow()}}>保存流程图</Button>
        </div>

      </Toolbar>
    );
  }
}

export default withPropsAPI(FlowToolbar);
@yinbanghui

**Comment by yinbanghui** [comment]
问题已经解决 感谢 @zsl1549

**Comment by raindroper** [comment]
你好，我这里出现了同样的问题，可不可以请教一下是如何解决的

**Comment by susieWang** [comment]
Koni, 绘制后，无法保存。this.props.propsAPI 为{}

**Comment by ShawLyon** [comment]
> 你好，我这里出现了同样的问题，可不可以请教一下是如何解决的

保存按钮放在GGEditor下面
