### ISSUE TITLE
 锚点样式如何配置？

### ISSUE THREAD

**Issue by yinbanghui** [gaoli/GGEditor#117]
## 这个功能解决了什么问题
锚点样式可配置
![image](https://user-images.githubusercontent.com/10389726/49430068-ff24b500-f7e4-11e8-8c65-deddafcc09ac.png)

## 你所期望的 API 是怎样的
锚点样式可配置

**Comment by gaoli** [comment]
@yinbanghui 请参照 [这里](https://www.yuque.com/antv/g6/detail-anchor)
