### ISSUE TITLE
Page Events里面  事件对象里的 action  怎么监听呢

### ISSUE THREAD

**Issue by ouaisheinie** [gaoli/GGEditor#119]
包括 add update remove changeData 等  那四种情况的监听

**Comment by gaoli** [comment]
@ouaisheinie 为什么要在事件对象中对 action 进行监听？能把你的使用场景描述再清楚些吗？谢谢

**Comment by wuhao930406** [comment]
删除/新增/修改 节点如何监听到事件？并且知道删除的是哪个节点？

**Comment by wqjiao** [comment]
怎么使用 事件对象 add update remove changeData
