### ISSUE TITLE
RegisterCommand 注册时config如何配置

### ISSUE THREAD

**Issue by 0end1** [gaoli/GGEditor#121]
![image](https://user-images.githubusercontent.com/19548631/49725828-a010e580-fca7-11e8-9fec-72dbd558ae6d.png)

**Comment by gaoli** [comment]
@0end1 命令的具体配置可以参考[这里](https://www.yuque.com/antv/g6-editor/dcqwpx)

**Comment by zhandouxiaojiji** [comment]
链接失效了 @gaoli
