### ISSUE TITLE
可以禁止整个画布的拖动吗

### ISSUE THREAD

**Issue by jisao** [gaoli/GGEditor#122]
## 你所期望的 API 是怎样的
目前自己配置好一个流程, 在详情里面展示, 是否可以禁止掉画布的拖动

**Comment by gaoli** [comment]
@jisao 画布拖动无法禁止的，但有 `readOnly` 模式 :)

**Comment by tdida** [comment]
@gaoli readOnly 是那个组件的参数，怎么设置

**Comment by gaoli** [comment]
@tdida https://github.com/gaoli/GGEditor/issues/89#issuecomment-432073910
