### ISSUE TITLE
关于修改之后打包问题

### ISSUE THREAD

**Issue by QuYunFengg** [gaoli/GGEditor#123]
我在项目基础之上修改了代码，我希望打包生成一个html，以供vue页面使用
我该如何打包，我使用start命令没有生成新的bundle.js 文件

请问下如何打包

**Comment by gaoli** [comment]
@QuYunFengg 

试试 `npm run build:demo`

**Comment by QuYunFengg** [comment]
你好 这个命令只是修改配置吧 没有进行打包  没有看到bundle.js的变化

**Comment by gaoli** [comment]
@QuYunFengg 

```
// 打包 bundle 文件（dist 目录）
npm run build 

// 打包 bundle 文件（demo/dist 目录）
npm run build:demo
```
