### ISSUE TITLE
有木有节点只能连接一次，第二次不能连接。

### ISSUE THREAD

**Issue by zsl1549** [gaoli/GGEditor#125]
![image](https://user-images.githubusercontent.com/32888522/50129352-73fef100-02b3-11e9-8c59-be394783bb14.png)
连接的锚点的方法 ，点击当前锚点 连接到下一个元素的锚点 ，获取不到二个节点的信息，返回null。 @gaoli

**Comment by zsl1549** [comment]
看了api 没找到，有木有阻止连线的功能。。

**Comment by gaoli** [comment]
@zsl1549 

可以换个思路，连线完成后，判断是否符合要求，不符合则直接执行 `undo` 命令回退：）

**Comment by zsl1549** [comment]
undo命令????       
![image](https://user-images.githubusercontent.com/32888522/50193199-9440b580-0370-11e9-9665-22370bd85b52.png) 自定义节点  怎么让他自动布局@gaoli

**Comment by gaoli** [comment]
@zsl1549 

http://ggeditor.com/docs/api/propsAPI.zh-CN.html

`executeCommand('undo')` 即回退命令，流程图暂时不支持自动布局：）

**Comment by zsl1549** [comment]
只能通过x，y轴来操作吗？ 通过g6的插件布局，这样支持吗？

**Comment by gaoli** [comment]
@zsl1549 这个暂时不支持：）
