### ISSUE TITLE
ant design pro搭建的项目，scss文件如何解析？

### ISSUE THREAD

**Issue by sy13277072001** [gaoli/GGEditor#128]
用的ant design pro 搭建的项目，没有webpack.config.base.js文件，只有webpackrc.js，不知道要怎么配置才能支持.scss文件，而且驼峰形式的样式名，在scss文件中用的是小写的-来替代的，不知道要怎么配置，ant design pro中的css文件是.less的。

![image](https://user-images.githubusercontent.com/25413638/50370238-1eda1c80-05de-11e9-891f-55501337feaf.png)

![image](https://user-images.githubusercontent.com/25413638/50370240-23063a00-05de-11e9-84cb-4ec30d43eb4b.png)

const path = require('path');

export default {
  entry: 'src/index.js',
  extraBabelPlugins: [
    ['import', { libraryName: 'antd', libraryDirectory: 'es', style: true }],
  ],
  env: {
    development: {
      extraBabelPlugins: ['dva-hmr'],
    },
  },
  alias: {
    components: path.resolve(__dirname, 'src/components/'),
  },
  ignoreMomentLocale: true,
  theme: './src/theme.js',
  html: {
    template: './src/index.ejs',
  },
  disableDynamicImport: true,
  publicPath: '/',
  hash: true,
  sass: true,
};

**Comment by gaoli** [comment]
@sy13277072001 

1.5.0 版本已经使用 Less 预处理 CSS :)
