### ISSUE TITLE
怎样调用撤退undo方法，命令不能使用。

### ISSUE THREAD

**Issue by zsl1549** [gaoli/GGEditor#129]
![image](https://user-images.githubusercontent.com/32888522/50384714-7cb45480-0703-11e9-84bc-604ce73afab5.png)
![image](https://user-images.githubusercontent.com/32888522/50384717-86d65300-0703-11e9-9afa-4fa0b220243e.png)
![image](https://user-images.githubusercontent.com/32888522/50384718-8ccc3400-0703-11e9-84f3-dcfbce052161.png)
![image](https://user-images.githubusercontent.com/32888522/50384721-9786c900-0703-11e9-9f0b-224c3d8096a4.png)

**Comment by gaoli** [comment]
@zsl1549 

使用的方式不对哦，请参照 [这里](http://ggeditor.com/docs/api/propsAPI.zh-CN.html) :)

**Comment by zsl1549** [comment]
![image](https://user-images.githubusercontent.com/32888522/50389119-b10a2e00-0760-11e9-976f-9330acd78e34.png)
看API不就是这样去写吗？ 麻烦大哥写个例子，看API就是这样写的呀！

**Comment by zsl1549** [comment]
@gaoli 
https://codesandbox.io/s/6v7oyonykw
这样写为什么出不来，就必须分开吗？不想要点击按钮  直接触发他的方法 这样不行吗？

**Comment by gaoli** [comment]
@zsl1549 

被 `withPropsAPI` 包裹的组件必须是 `GGEditor` 的子元素 :)

**Comment by zsl1549** [comment]
谢谢大哥！  是我太笨了。。。。。。。。。。。。。

**Comment by sy13277072001** [comment]
> @zsl1549
> 
> 被 `withPropsAPI` 包裹的组件必须是 `GGEditor` 的子元素 :)

按照你的方式，方法executeCommand能拿到，但是在执行executeCommand('undo');的时候，会出现如下图的错误，是什么原因呢
![image](https://user-images.githubusercontent.com/25413638/51653188-5bc67400-1fcd-11e9-9263-f571c3cd262f.png)
