### ISSUE TITLE
移除Guide，读取数据， getStyle is not a function

### ISSUE THREAD

**Issue by tdida** [gaoli/GGEditor#132]
## 版本

v1.3.5

## 环境

macOS 10.14.3 Beta (18D32a)
Google Chrome 71.0.3578.98
React 16.7

## 重现链接

[![Edit 9o670kk2kw](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/9o670kk2kw)

## 重现步骤

点击移除mask、读取数据按钮，查看控制台报错

## 期望的结果是什么

无报错

## 实际的结果是什么

` getStyle is not a function`

**Comment by gaoli** [comment]
@tdida 没有出现报错信息呢？

**Comment by tdida** [comment]
@gaoli DevTools 有报错信息，codesandbox 的 Console 不知道为啥没有

**Comment by gaoli** [comment]
@tdida 升级至 2.0.0 版本，即可修复问题 :)
