### ISSUE TITLE
如何在节点上添加checkbox用来选中单个节点，多选后如何获取多选的节点及其连接的流程方向

### ISSUE THREAD

**Issue by sy13277072001** [gaoli/GGEditor#135]
## 版本

> 请检查问题是否存在于最新版本中

## 环境

> 系统、浏览器、React 等版本信息

## 重现链接

> 最小化重现错误以便精准定位问题，例如：[Flow](https://codesandbox.io/s/m2v96ok1p) / [Mind](https://codesandbox.io/s/1z6vp25xz3)

## 重现步骤

> 清晰的重现步骤以便迅速定位问题

**Comment by gaoli** [comment]
提问前请先仔细阅读[文档](http://ggeditor.com/README.zh-CN.html)，如遇问题请提供重现[演示](https://codesandbox.io/s/m2v96ok1p)

这样才能迅速地定位问题，谢谢配合：）
