### ISSUE TITLE
在page的flow/index.js文件中无法调用到withPropsAPI中的方法？看过了所有相关的issue都无法打印出withPropsAPI中的方法

### ISSUE THREAD

**Issue by sy13277072001** [gaoli/GGEditor#136]
## 版本

> 请检查问题是否存在于最新版本中

## 环境

> 系统、浏览器、React 等版本信息

## 重现链接

> 最小化重现错误以便精准定位问题，例如：[Flow](https://codesandbox.io/s/m2v96ok1p) / [Mind](https://codesandbox.io/s/1z6vp25xz3)

## 重现步骤

> 清晰的重现步骤以便迅速定位问题

**Comment by gaoli** [comment]
提问前请先仔细阅读[文档](http://ggeditor.com/README.zh-CN.html)，如遇问题请提供重现[演示](https://codesandbox.io/s/m2v96ok1p)

这样才能迅速地定位问题，谢谢配合：）

**Comment by gaoli** [comment]
参见 [常见问题](https://github.com/gaoli/GGEditor/issues/130) 如何使用方法

**Comment by sy13277072001** [comment]
> 参见 [常见问题](https://github.com/gaoli/GGEditor/issues/130) 如何使用方法


问题有三个，都在注释里面，谢谢
https://codesandbox.io/s/wyy1lpoyww
