### ISSUE TITLE
delete删除连接线 的方法

### ISSUE THREAD

**Issue by zsl1549** [gaoli/GGEditor#140]
![image](https://user-images.githubusercontent.com/32888522/50503075-16328c00-0a9f-11e9-9262-083de90311a3.png)
config 的配置项文档去那了  需要传什么参数可以删除吗？ 或者有什么更好的方法 实现删除吗？ @gaoli @tennisonchan

**Comment by gaoli** [comment]
@zsl1549 请参照 [常用问题](https://github.com/gaoli/GGEditor/issues/130) - 如何注册命令

**Comment by gaoli** [comment]
@zsl1549 在线演示中有详细的说明呢 :)

```jsx
import React from "react";
import { RegisterCommand } from "gg-editor";

class CustomCommand extends React.Component {
  render() {
    const config = {
      // 是否进入列队，默认为 true
      queue: true,

      // 命令是否可用
      enable(/* editor */) {
        return true;
      },

      // 正向命令逻辑
      execute(/* editor */) {
        console.log("执行正向命令");
      },

      // 反向命令逻辑
      back(/* editor */) {
        console.log("执行反向命令");
      },

      // 快捷按键配置
      shortcutCodes: [["metaKey", "s"], ["ctrlKey", "s"]]
    };

    return <RegisterCommand name="customCommand" config={config} />;
  }
}

export default CustomCommand;
```

**Comment by zsl1549** [comment]
谢谢，弱弱的问下 点击边 怎么改变他的 样式 变的宽度大点。。文档没找到
![image](https://user-images.githubusercontent.com/32888522/50510849-3f1a4780-0ac6-11e9-8840-295056f9e0ea.png)

**Comment by gaoli** [comment]
@zsl1549 点击的时候更新下 edge 的 model：

```json
edges: [{
  ...
  "style": {
    "lineWidth": 10
  },
}],
```

不同的问题请分开提问，谢谢：）

**Comment by eggachecat** [comment]
@gaoli 请问要怎么知道是这样操作的..有比较系统的文档吗..非常感谢

**Comment by eggachecat** [comment]
somehow 我在[这里](https://github.com/alibaba/GGEditor/blob/347e23110af76ac9abf597d1942f5d4ba953d6fe/src/shape/edges/bizFlowEdge.ts#L12) 找到了好像可以配置的选项...不知道会不会有这样详细的文档呢?
