### ISSUE TITLE
read方法无法获取

### ISSUE THREAD

**Issue by sy13277072001** [gaoli/GGEditor#145]
## 版本

> 请检查问题是否存在于最新版本中

## 环境

> 系统、浏览器、React 等版本信息

## 重现链接

> 最小化重现错误以便精准定位问题，例如：[Flow](https://codesandbox.io/s/m2v96ok1p) / [Mind](https://codesandbox.io/s/1z6vp25xz3)

## 重现步骤

https://codesandbox.io/s/30jrqvn2yp

> 清晰的重现步骤以便迅速定位问题

**Comment by gaoli** [comment]
@sy13277072001 可以参照这个 [DEMO](https://codesandbox.io/s/r4kzkn441m)

**Comment by sy13277072001** [comment]
> @sy13277072001 可以参照这个 [DEMO](https://codesandbox.io/s/r4kzkn441m)

这里的save方法还是通过组件引入然后点击的时候才能存在，在页面的componentDidMount是没办法打印的。

**Comment by gaoli** [comment]
@sy13277072001 `componentDidMount` 不代表编辑器已经初始化完成 :)

**Comment by sy13277072001** [comment]
> @sy13277072001 `componentDidMount` 不代表编辑器已经初始化完成 :)

好的，我明白了。谢谢高大哥
