### ISSUE TITLE
RegisterNode 方法的 config  该如何配置呢？

### ISSUE THREAD

**Issue by ouaisheinie** [gaoli/GGEditor#149]
## 这个功能解决了什么问题
  想要定制一种节点类型
## 你所期望的 API 是怎样的
  可以在顶部或者底部显示节点类型

**Comment by gaoli** [comment]
参照这个 [DEMO](https://codesandbox.io/s/4j62moqy0w)

**Comment by ouaisheinie** [comment]
谢谢
