### ISSUE TITLE
RegisterBehaviour 如何使用？

### ISSUE THREAD

**Issue by liudongrong** [gaoli/GGEditor#152]
请问如何使用RegisterBehaviour？官方G6-Editor文档并不存在这个API，仅存在于G6

**Comment by gaoli** [comment]
GGEditor 本身就是基于 `G6` :)

**Comment by liudongrong** [comment]
hh，但是用了registerbehavior没有任何反应……已换其他解决方案

**Comment by liudongrong** [comment]
求助另一个问题，如何根据触命令的节点设置命令的enable？目前似乎没办法获取触发命令的对象

**Comment by gaoli** [comment]
@liudongrong 

https://codesandbox.io/s/xp9q6yxyyp

可以通过 `propsAPI.getSelected()` 获取相应的 Item :)

**Comment by gaoli** [comment]
@liudongrong 

上下文中的 `this` 可以拿到命令对象自身 :)

**Comment by liudongrong** [comment]
谢谢大佬，我去试试
