### ISSUE TITLE
RegisterEdge文档不全，怎么使用？

### ISSUE THREAD

**Issue by zsl1549** [gaoli/GGEditor#157]
![image](https://user-images.githubusercontent.com/32888522/50889562-3fee9a00-1433-11e9-8478-84c2714ee25b.png)
![image](https://user-images.githubusercontent.com/32888522/50889591-51d03d00-1433-11e9-9b51-029ed6dc267f.png)
不生效啊？https://www.yuque.com/antv/g6/custom-edge#_%E6%A6%82%E8%BF%B0
没看明白，大哥有木有具体的实例啊？ @gaoli

**Comment by zsl1549** [comment]
@gaoli 指导一下呗

**Comment by gaoli** [comment]
亲，请参见 [常见问题](https://github.com/gaoli/GGEditor/issues/130) 中的 **如何定义边线** 部分 :)

**Comment by suwu150** [comment]
> 亲，请参见 [常见问题](https://github.com/gaoli/GGEditor/issues/130) 中的 **如何定义边线** 部分 :)

请问脑图中边线(连接线)形状能进行更改吗?该如何更改
