### ISSUE TITLE
mind (脑图) 的根节点拿不到事件对象

### ISSUE THREAD

**Issue by jiechud** [gaoli/GGEditor#161]
![image](https://user-images.githubusercontent.com/9709396/51223748-1a571880-197e-11e9-818e-138fed643175.png)

脑图的根节点事件对象获取不多item

![image](https://user-images.githubusercontent.com/9709396/51223785-39ee4100-197e-11e9-8be9-08e3babab630.png)

**Comment by jiechud** [comment]
升级到 2.0.1 可以了

**Comment by gaoli** [comment]
@jiechud 是 2.0.0 的 bug，昨天刚刚修复 :)
