### ISSUE TITLE
gg-editor-core 开源

### ISSUE THREAD

**Issue by shenzhim** [gaoli/GGEditor#165]
gg-editor-core 这个库能够开源么？不开源的话，毕竟有些顾虑，不太敢用啊。

**Comment by gaoli** [comment]
@shenzhim GGEditor 2.x 会配合 G6 3.0 进行重构，到时候也不会再依赖 `gg-editor-core` 这个库 :)

**Comment by yinjun322** [comment]
什么时候ggeditor会出来呢

**Comment by BH-M87** [comment]
如果不开源，这个库整体用下来会有顾虑。
