### ISSUE TITLE
demo无法运行

### ISSUE THREAD

**Issue by 289202471** [gaoli/GGEditor#170]
## 版本

> 请检查问题是否存在于最新版本中

## 环境

> 系统、浏览器、React 等版本信息

## 重现链接

> 最小化重现错误以便精准定位问题，例如：[Flow](https://codesandbox.io/s/m2v96ok1p) / [Mind](https://codesandbox.io/s/1z6vp25xz3)

## 重现步骤

> 清晰的重现步骤以便迅速定位问题

## 期望的结果是什么
![image](https://user-images.githubusercontent.com/29940173/52043151-e2ed8c00-2579-11e9-8dda-5fdca75bd3ac.png)

## 实际的结果是什么
![image](https://user-images.githubusercontent.com/29940173/52043132-d5380680-2579-11e9-9167-81b5e8d376ee.png)

**Comment by gaoli** [comment]
@289202471 请提供你的环境信息
