### ISSUE TITLE
[Question] How to get an array or json file of the graph?

### ISSUE THREAD

**Issue by jahirfiquitiva** [gaoli/GGEditor#172]
Hello

I want to know if it's possible to get the graph data (all nodes and connections or edges) as a json or an array.

Thanks in advance.

**Comment by gaoli** [comment]
@jahirfiquitiva 

http://ggeditor.com/docs/api/propsAPI.en-US.html

You can get the graph data through `save()` method.

**Comment by jahirfiquitiva** [comment]
Is there an example where I can test the output format?

**Comment by gaoli** [comment]
@jahirfiquitiva 

https://codesandbox.io/s/r4kzkn441m

You can refer to the demo.

**Comment by jahirfiquitiva** [comment]
Thanks for the help
