### ISSUE TITLE
[Question] How to limit edges creation for all nodes?

### ISSUE THREAD

**Issue by jahirfiquitiva** [gaoli/GGEditor#177]
Hello

Basically, I would like all nodes to have max 1 outgoing edge and 1 incoming edge, instead of the 4 currently possible.

Is that possible? If so, how?

Thanks in advance!

**Comment by gaoli** [comment]
@jahirfiquitiva 

<img src="https://user-images.githubusercontent.com/780578/56350611-c3bbdd80-61fd-11e9-88c2-588ad12c06c7.png" width="200" />

You can set this by configuring the `anchor` property, like this [demo](https://codesandbox.io/s/qv7yrwwkjw) :)

**Comment by jahirfiquitiva** [comment]
Thanks for the example 😀
