### ISSUE TITLE
为什么样式不生效呢

### ISSUE THREAD

**Issue by jiaoxing** [gaoli/GGEditor#178]
按照你的写法，className={styles.flow}这样去写的时候，样式不生效，这是为什么呢

**Comment by gaoli** [comment]
@jiaoxing 能给个简单的 DEMO 帮助我们定位吗？

**Comment by suwu150** [comment]
> 按照你的写法，className={styles.flow}这样去写的时候，样式不生效，这是为什么呢

我是集成到我们项目中,也是不起作用,我最后使用了如下方式,能够起作用
```
className='flow'
```

**Comment by gaoli** [comment]
@jiaoxing @suwu150 可能参照 [项目](https://github.com/gaoli/GGEditor/blob/master/tools/webpack.config.base.js#L17) 的 webpack `css-loader` 配置 :)
