### ISSUE TITLE
如何保存GGEditor的编辑的Flow流程图？

### ISSUE THREAD

**Issue by lvzheng0404** [gaoli/GGEditor#181]
## 这个功能解决了什么问题
可以将GGEditor编辑的流程图保存起来；
## 你所期望的 API 是怎样的
可以提供一个类似删除按钮那样的保存按钮，将编辑好的流程图保存起来

**Comment by gaoli** [comment]
@lvzheng0404 可以参照这个 [DEMO](https://codesandbox.io/s/r4kzkn441m)
