### ISSUE TITLE
ant design pro 里使用GGEditor FlowPage,样式无法加载

### ISSUE THREAD

**Issue by lvzheng0404** [gaoli/GGEditor#183]
ant design pro 里使用GGEditor FlowPage,样式无法加载
![image](https://user-images.githubusercontent.com/35189771/53796940-1f911680-3f70-11e9-88ac-49a26fb5161f.png)

**Comment by lvzheng0404** [comment]
@gaoli

**Comment by gaoli** [comment]
@lvzheng0404 能否提供一个 DEMO 帮助定位问题？

**Comment by lvzheng0404** [comment]
好的，我整理一下发给你，能否加个QQ方便联系0.0？   qq号：597585301
----- 原始邮件 -----
发件人：高力 <notifications@github.com>
收件人：gaoli/GGEditor <GGEditor@noreply.github.com>
抄送人：lvzheng0404 <lvzheng0404@sina.com>,  Mention <mention@noreply.github.com>
主题：Re:_[gaoli/GGEditor]_ant_design_pro_里使用GGEditor_FlowPage,样式无法加载_(#183)
日期：2019年03月06日 17点08分

@lvzheng0404 能否提供一个 DEMO 帮助定位问题？



&mdash;

**Comment by lvzheng0404** [comment]
@gaoli 您好，问题项目发你qq邮箱了（3071730@qq.com），麻烦看一下，多谢多谢。

**Comment by lvzheng0404** [comment]
@gaoli

**Comment by eviem** [comment]
我的也是ant pro 项目，样式加载错误，需要修改你的样式引入方式。

**Comment by hxynet** [comment]
我的也是antd pro项目，按示例添加Toolbar后，里面的command没有图标，不知如何解决。

**Comment by lvzheng0404** [comment]
> 我的也是ant pro 项目，样式加载错误，需要修改你的样式引入方式。

如何修改呢？

**Comment by eviem** [comment]
> > 我的也是ant pro 项目，样式加载错误，需要修改你的样式引入方式。
> 
> 如何修改呢？

参考  https://blog.csdn.net/sinat_15951543/article/details/88635100

**Comment by lvzheng0404** [comment]
> > > 我的也是ant pro 项目，样式加载错误，需要修改你的样式引入方式。
> > 
> > 
> > 如何修改呢？
> 
> 参考 https://blog.csdn.net/sinat_15951543/article/details/88635100

您好，按照csdn文章里的改了，还是不行，能加个联系方式，请教一下吗？qq：597585301  
微信：a597585301

**Comment by hxynet** [comment]
> > > > 我的也是ant pro 项目，样式加载错误，需要修改你的样式引入方式。
> > > 
> > > 
> > > 如何修改呢？
> > 
> > 
> > 参考 https://blog.csdn.net/sinat_15951543/article/details/88635100
> 
> 您好，按照csdn文章里的改了，还是不行，能加个联系方式，请教一下吗？qq：597585301
> 微信：a597585301

同样改了也不行，实在不行我就准备在Tooltip里加<Icon></Icon>了,象下面这种：
<Command name="undo">
          <Tooltip title="撤销" placement="bottom" overlayClassName={styles.tooltip}>
            <Icon/>
          </Tooltip>
</Command>
但这样好象disable时不会灰色显示。

**Comment by gaoli** [comment]
@lvzheng0404 @eviem @hxynet 

不好意思，最近较忙，未能即使作解答，我已联系好 ant design pro 的相关同学，

今天会 Pull 集成 GGEditor 的集成版本：）

**Comment by lvzheng0404** [comment]
> @lvzheng0404 @eviem @hxynet
> 
> 不好意思，最近较忙，未能及时作解答，我已联系好 ant design pro 的相关同学，
> 
> 今天会 Pull 集成 GGEditor 的集成版本：）

非常感谢。

**Comment by gaoli** [comment]
@lvzheng0404 @eviem @hxynet 

大家可以直接参考这个 [PR](https://github.com/ant-design/ant-design-pro/pull/3810) :)
