### ISSUE TITLE
流程图连接线默认是圆曲线，如果把默认修改为圆角折线，而不是每条线手工修改

### ISSUE THREAD

**Issue by flg717** [gaoli/GGEditor#184]
## 这个功能解决了什么问题
流程图使用中，业务场景不一致，连接线要求也不一样，应该提供一个钩子，让开发者直接设置默认连接线
## 你所期望的 API 是怎样的
流程图连接线默认应该是可以有开发者去设置

**Comment by eviem** [comment]
+1，我也是想知道这个问题的答案。

**Comment by eviem** [comment]
@gaoli  紧抱大腿

**Comment by gaoli** [comment]
@flg717 可以参考以下配置 :)

```jsx
<Flow graph={{ edgeDefaultShape: 'flow-polyline-round' }} />
```

**Comment by skdwangyao** [comment]
> @flg717 可以参考以下配置 :)
> 
> ```js-jsx
> <Flow graph={{ edgeDefaultShape: 'flow-polyline-round' }} />
> ```

edgeDefaultShape 属性从哪看到的，g6文档没有
