### ISSUE TITLE
将demo里的FlowPage等样例放到gg-editor中

### ISSUE THREAD

**Issue by lvzheng0404** [gaoli/GGEditor#186]
## 这个功能解决了什么问题
直接通过gg-editor引用FlowPage组件
## 你所期望的 API 是怎样的
可以将demo里的FlowPage，MindPage等样例封装好，放入gg-editor中，用户可以很方便的直接从gg-editor中直接引用这些组件。

**Comment by lvzheng0404** [comment]
@gaoli

**Comment by gaoli** [comment]
@lvzheng0404 感谢你的意见，我们后期计划集成至 [ANT DESIGN PRO](https://pro.ant.design/index-cn)

**Comment by lvzheng0404** [comment]
集成后请@我，我们这有需求要用，谢谢。
----- 原始邮件 -----
发件人：高力 <notifications@github.com>
收件人：gaoli/GGEditor <GGEditor@noreply.github.com>
抄送人：吕铮 <lvzheng0404@sina.com>,  Mention <mention@noreply.github.com>
主题：Re:_[gaoli/GGEditor]_将demo里的FlowPage等样例放到gg-editor中_(#186)
日期：2019年03月15日 17点40分

@lvzheng0404 感谢你的意见，我们后期计划集成至 ANT DESIGN PRO



&mdash;
