### ISSUE TITLE
在历史项目引入，用的react15版，引入后报错，这个流程图用的是react16，请问如何才能在react15中使用呢

### ISSUE THREAD

**Issue by Moonphy** [gaoli/GGEditor#188]
## 在历史项目引入，用的react15版，引入后报错，这个流程图用的是react16，请问如何才能在react15中使用呢

> 我自己的项目用的react15，升级16版很麻烦，东西太多。
> 要怎样才能在react15版中使用这个流程图呢？

**Comment by suwu150** [comment]
我使用的16.2,不知道是不是版本的问题,还是webpack的问题,会遇到下面问题
![image](https://user-images.githubusercontent.com/20339760/56008479-f43bdd00-5d0e-11e9-87ec-8357a307b8c2.png)
![image](https://user-images.githubusercontent.com/20339760/56008486-f9992780-5d0e-11e9-9ee8-59f9e1c84df2.png)

**Comment by gaoli** [comment]
@Moonphy @suwu150 当前版本仅支持 React 16.3 +
