### ISSUE TITLE
 Can't resolve '@babel/runtime/helpers/createClass' 

### ISSUE THREAD

**Issue by suwu150** [gaoli/GGEditor#195]
## 版本
> "gg-editor": "^2.0.3",

## 环境

> macos 、谷歌浏览器、React 等版本信息
    "react": "16.2.0",
    "react-dom": "16.2.0",
    "react-grid-layout": "0.16.6",
    "react-router-dom": "4.2.2",
其中
    "babel-core": "6.26.0",
    "babel-eslint": "8.0.3",
    "babel-loader": "7.1.2",
    "babel-plugin-import": "1.6.3",
    "babel-plugin-transform-decorators-legacy": "1.3.4",
    "babel-polyfill": "6.26.0",
    "babel-preset-env": "1.6.1",
    "babel-preset-es2015": "6.24.1",
    "babel-preset-react": "6.24.1",
    "babel-preset-stage-0": "6.24.1",

重现步骤;
使用该命令import GGEditor, { Mind } from 'gg-editor';导入暂未在render方法中使用时,就已经提示如下错误

## 期望的结果是什么
期望不报错,能够正常导入
## 实际的结果是什么
1.
![image](https://user-images.githubusercontent.com/20339760/55845662-62e53300-5b75-11e9-9af5-c9924c32942b.png)

2.
![image](https://user-images.githubusercontent.com/20339760/55928648-1d476980-5c4c-11e9-8d76-8496f2fbcbd8.png)

3.
![image](https://user-images.githubusercontent.com/20339760/55928656-26d0d180-5c4c-11e9-9f2c-1ab97a02c9f8.png)

**Comment by gaoli** [comment]
@suwu150 你的 webpack 与 babel 配置能贴出来看看吗？

**Comment by suwu150** [comment]
> @suwu150 你的 webpack 与 babel 配置能贴出来看看吗？
    "babel-core": "6.26.0",
    "babel-eslint": "8.0.3",
    "babel-loader": "7.1.2",
    "babel-plugin-import": "1.6.3",
    "babel-plugin-transform-decorators-legacy": "1.3.4",
    "babel-polyfill": "6.26.0",
    "babel-preset-env": "1.6.1",
    "babel-preset-es2015": "6.24.1",
    "babel-preset-react": "6.24.1",
    "babel-preset-stage-0": "6.24.1",
    "html-webpack-plugin": "2.30.1",
    "imports-loader": "0.7.1",
    "less": "2.7.3",
    "less-loader": "4.0.5",
    "postcss-loader": "2.0.9",
    "style-loader": "0.19.0",
    "url-loader": "0.6.2",
    "webpack": "3.10.0",
    "webpack-dev-server": "2.11.1"

这个是一些配置

**Comment by gaoli** [comment]
> > @suwu150 你的 webpack 与 babel 配置能贴出来看看吗？
> > "babel-core": "6.26.0",
> > "babel-eslint": "8.0.3",
> > "babel-loader": "7.1.2",
> > "babel-plugin-import": "1.6.3",
> > "babel-plugin-transform-decorators-legacy": "1.3.4",
> > "babel-polyfill": "6.26.0",
> > "babel-preset-env": "1.6.1",
> > "babel-preset-es2015": "6.24.1",
> > "babel-preset-react": "6.24.1",
> > "babel-preset-stage-0": "6.24.1",
> > "html-webpack-plugin": "2.30.1",
> > "imports-loader": "0.7.1",
> > "less": "2.7.3",
> > "less-loader": "4.0.5",
> > "postcss-loader": "2.0.9",
> > "style-loader": "0.19.0",
> > "url-loader": "0.6.2",
> > "webpack": "3.10.0",
> > "webpack-dev-server": "2.11.1"
> 
> 这个是一些配置

这个是你的以来配置呢，我要的是 webpack 与 babel 的配置文件内容 :)

**Comment by suwu150** [comment]
> > > @suwu150 你的 webpack 与 babel 配置能贴出来看看吗？
> > > "babel-core": "6.26.0",
> > > "babel-eslint": "8.0.3",
> > > "babel-loader": "7.1.2",
> > > "babel-plugin-import": "1.6.3",
> > > "babel-plugin-transform-decorators-legacy": "1.3.4",
> > > "babel-polyfill": "6.26.0",
> > > "babel-preset-env": "1.6.1",
> > > "babel-preset-es2015": "6.24.1",
> > > "babel-preset-react": "6.24.1",
> > > "babel-preset-stage-0": "6.24.1",
> > > "html-webpack-plugin": "2.30.1",
> > > "imports-loader": "0.7.1",
> > > "less": "2.7.3",
> > > "less-loader": "4.0.5",
> > > "postcss-loader": "2.0.9",
> > > "style-loader": "0.19.0",
> > > "url-loader": "0.6.2",
> > > "webpack": "3.10.0",
> > > "webpack-dev-server": "2.11.1"
> > 
> > 
> > 这个是一些配置
> 
> 这个是你的以来配置呢，我要的是 webpack 与 babel 的配置文件内容 :)

.babelrc
```
{
  "presets": [
    "es2015",
    "react",
    "stage-0"
  ],
  "plugins": [
    ["transform-decorators-legacy"],
    ["import", { "libraryName": "antd", "libraryDirectory": "es", "style": true }]
  ],
  "ignore": [
    "react-dom.development.js"
  ]
}
```
webpack-dev
```
module.exports = {
    devtool: 'cheap-module-eval-source-map',
    entry: {
        app: [
          path.resolve(__dirname, '../src/lib/string'),
          path.resolve(__dirname, '../src/lib/Math'),
          path.resolve(__dirname, '../src/index')
        ],
        vendor: [require.resolve('babel-polyfill'), 'react', 'react-dom', 'antd', 'react-router-dom']
    },
    output: {
        path: path.resolve(__dirname, '../static'),
        filename: "[name].js"
    },
    resolve: {
      alias: {
        'appalias': path.resolve(__dirname, '../index')
      }
    },
    plugins: [
        new webpack.optimize.CommonsChunkPlugin({name: 'vendor',  filename: 'vendor.js'}),
        new RofaceInterpolateHtmlPlugin({
          baseUrl: getBaseUrl
        }),
        new HtmlWebpackPlugin({
            inject: true,
            template: path.resolve(__dirname, '../public/main.html'),
            filename: 'main.html',
            chunks: ['vendor','app']
        }),
        new ScriptExtHtmlPlugin({
            defaultAttribute: 'defer'
        }),
        new OpenBrowserPlugin({ url: `${defaultConfig.protocol}://${defaultConfig.host}:${defaultConfig.port}` }),
        new ExtractTextPlugin('style.css')
    ],
    externals: {
      jquery: 'jQuery'
    },
    module: {
        loaders: [
            {
                test: /\.(js|tsx|jsx)$/,
                exclude: /node_modules/,
                loader: 'babel-loader'
            },
            {
                test: /\.(js|tsx|jsx)$/,
                exclude: /node_modules/,
                loader: "eslint-loader"
            },
            {
                test: /\.css$/,
                loader: ExtractTextPlugin.extract({
                    fallback: "style-loader",
                    use: [ "css-loader",
                      { loader: "postcss-loader", options: { plugins: () => [ require('autoprefixer')({
                            browsers: [
                              '>1%',
                              'last 4 versions',
                              'Firefox ESR',
                              'not ie < 9', // React doesn't support IE8 anyway
                            ]
                          }) ]}}
                     ]
                })
            },
            {
                test: /\.less$/,
                loader: ExtractTextPlugin.extract({
                    fallback: 'style-loader',
                    use: ["css-loader", { loader: "postcss-loader", options: { plugins: () => [ require('autoprefixer')({
                          browsers: [
                            '>1%',
                            'last 4 versions',
                            'Firefox ESR',
                            'not ie < 9', // React doesn't support IE8 anyway
                          ]
                        }) ]}},
                      { loader: 'less-loader', options: {
                        "modifyVars":{ '@icon-url': "'"+ defaultConfig.icon + "'",'@font-size-base':config.fontSize,
                          '@tableCellPadding':config.tableCellPadding,'@tableHeadFontSize':config.tableHeadFontSize,
                          '@font-size-text':config.cusFontSizeText,'@input-height-base':config.inputHeightBase,
                          '@padding-md':config.btnPadding,'@btn-height-base':config.btnHeight,
                          '@menuHeight':config.menuHeight,'@formItemBottom':config.formItemBottom,
                          '@inputHeightBase':config.inputHeightBase,'@legendBottom':config.legendBottom, '@font-family': config.fontFamily}
                      }}]
                })
            },
            {
                test: /\.(png|jpg|svg|gif)$/,
                loader: 'url-loader',
                options: {
                  limit: 8192
                }
            },
            {
                test: require.resolve('../src/lib/config'),
                loader: "imports-loader?baseUrl=>'',staticUrl=>'" + config.staticUrl + "',customPage=>'" + config.customPage + "'"
            }
        ]
    }
}
```

**Comment by gaoli** [comment]
@suwu150 你需要升级你的 babel 版本到 7.x

**Comment by suwu150** [comment]
> @suwu150 你需要升级你的 babel 版本到 7.x

请问有没有不升级,兼容的方法进行处理,我这边项目稳定运行了有段时间了,现在不适合升级这些版本,有没有其他方式进行兼容使gg-editor
