### ISSUE TITLE
在项目中引用GG-Editor,编译时出现这种警告

### ISSUE THREAD

**Issue by zhangpengfa666** [gaoli/GGEditor#196]
![20190411104420](https://user-images.githubusercontent.com/43570454/55927369-61843b00-5c47-11e9-8347-c8fd94a6bccb.png)

**Comment by gaoli** [comment]
@zhangpengfa666 请附下你的 `package.json` 文件 :)

**Comment by zhangpengfa666** [comment]
不好意思麻烦你了,已经解决了
