### ISSUE TITLE
请问roots节点的样式怎么更改

### ISSUE THREAD

**Issue by suwu150** [gaoli/GGEditor#208]
请问roots节点的样式怎么更改,图标怎么添加,背景色怎么修改

**Comment by Marckon** [comment]
参考这个[Demo](https://codesandbox.io/s/mm21wymnmx)

**Comment by suwu150** [comment]
> 参考这个[Demo](https://codesandbox.io/s/mm21wymnmx)

谢谢,但是我按照这样的方法设置之后,发现跟节点无法选中了,无法进行选中,点击选中之后也不会渲染节点详情

**Comment by suwu150** [comment]
为什么会出现这种不能选中的情况?

**Comment by Marckon** [comment]
> 为什么会出现这种不能选中的情况?

刚才那个Demo只是一个小例子，其实你只需要知道有`mind-root`和`rootShape`这样的配置项就可以啦，具体还是要仿照Demo里对`mind-base`节点的`conifg`配置进行更改。🙂

**Comment by suwu150** [comment]
好的,谢谢,同时希望能够整理下配置项都有哪些,方便直接使用
