### ISSUE TITLE
自定义时,请问能否直接使用antd-design中icon的图标

### ISSUE THREAD

**Issue by suwu150** [gaoli/GGEditor#209]
自定义时,请问能否直接使用antd-design中icon的图标?
![image](https://user-images.githubusercontent.com/20339760/56562069-300e5680-65db-11e9-98eb-ebe53d5fa903.png)

**Comment by Marckon** [comment]
你可以参考[antvis/g-shapeimage](https://github.com/antvis/g#shapeimage)
这里说明了`img`应该是一个`url`链接，你这种写法暂时应该是不支持的。
