### ISSUE TITLE
如何通过 DetailPanel 以及 this.props 编辑边的属性？

### ISSUE THREAD

**Issue by caicre** [gaoli/GGEditor#210]
console.log 打印 this.props 后，没有找到 getSelected 和 updateItem 方法

**Comment by caicre** [comment]
<DetailPanel className={styles.detailPanel}>
                <EdgePanel>
                    <EdgeDetail/>
                </EdgePanel>
            </DetailPanel>

    class EdgeDetail extends React.Component{
        render(){
            const {form, getSelected, updateItem}=this.props;
        }
    }

这样不能获取选中的边，然后更新边的属性吗？

**Comment by caicre** [comment]
import {withPropsAPI} from 'gg-editor';

    const {form,propsAPI}=this.props;

    export default Form.create()(withPropsAPI(NodeDetail));

通过上述方式可以在 propsAPI 中找到 getSelected, update

参考了 https://github.com/Marckon/GGEditorDemo 的代码，但是其中 EdgeDetail 的实现有一点小 bug.  需要通过上述方式修改。

**Comment by caicre** [comment]
希望能够提供更为系统的说明和 demo，事实上我建议联系 https://github.com/Marckon/GGEditorDemo 的作者，其中的功能相当完善.

**Comment by Marckon** [comment]
我这个项目已经很早了，GGEditor之前是依赖G6Editor的，现在改为依赖GGEditorCore了。之前项目中的一些实现办法在当前的GGEditor版本中不一定支持了。
