### ISSUE TITLE
请问有没有类似的开源组件，我想看一下edge的具体实现。谢谢。

### ISSUE THREAD

**Issue by liuliuLiu161** [gaoli/GGEditor#221]

**Comment by Marckon** [comment]
参考[antv/g & antv/g6](https://github.com/antvis)

**Comment by liuliuLiu161** [comment]
谢谢。




------------------ 原始邮件 ------------------
发件人: "Liu CZ"<notifications@github.com>; 
发送时间: 2019年5月14日(星期二) 上午9:23
收件人: "gaoli/GGEditor"<GGEditor@noreply.github.com>; 
抄送: "eth"<1432434841@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [gaoli/GGEditor] 请问有没有类似的开源组件，我想看一下edge的具体实现。谢谢。 (#221)




参考antv/g & antv/g6
