### ISSUE TITLE
Props API 中 add 方法的使用demo

### ISSUE THREAD

**Issue by zongdayong** [gaoli/GGEditor#226]
您好，有时间请帮忙提供Props API 中 add 方法的使用demo， 谢谢

**Comment by gaoli** [comment]
@zongdayong 

命令的使用可以统一参考这个 [DEMO](https://codesandbox.io/s/r4kzkn441m) :)

**Comment by zongdayong** [comment]
收到 谢谢


------------------ 原始邮件 ------------------
发件人: "高力"<notifications@github.com>;
发送时间: 2019年5月14日(星期二) 上午9:06
收件人: "gaoli/GGEditor"<GGEditor@noreply.github.com>;
抄送: "咿呀咿呀哟！！！"<1007074207@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [gaoli/GGEditor] Props API 中 add 方法的使用demo (#226)




@zongdayong
 
命令的使用可以统一参考这个 DEMO :)

**Comment by zongdayong** [comment]
在使用g6的grid插件时，指定内置的drag-canvas事件后，画布拖拽出现空白，请问这种情况在gg-editor中是如何处理的？能不能指导一下，万分感谢
我想要的效果是画布能一直拖动，或者到达边界后能禁止画布拖动
问题截图：



------------------ 原始邮件 ------------------
发件人: "高力"<notifications@github.com>;
发送时间: 2019年5月14日(星期二) 上午9:06
收件人: "gaoli/GGEditor"<GGEditor@noreply.github.com>;
抄送: "咿呀咿呀哟！！！"<1007074207@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [gaoli/GGEditor] Props API 中 add 方法的使用demo (#226)




@zongdayong
 
命令的使用可以统一参考这个 DEMO :)
