### ISSUE TITLE
节点文字内容超长

### ISSUE THREAD

**Issue by chrisovu** [gaoli/GGEditor#228]
## 这个功能解决了什么问题
节点文字内容超长显示
## 你所期望的 API 是怎样的
对于节点里面文字超长是否有处理方式，是否支持换行？

**Comment by chrisovu** [comment]
对于节点里面文字超长是否有处理方式，是否支持换行？

**Comment by gaoli** [comment]
@chrisovu 使用下面的方法换行文本 :)

```js
const canvas = document.createElement('canvas');
const canvasContext = canvas.getContext('2d');

export function optimizeMultilineText(text, font, maxWidth = 320) {
  canvasContext.font = font;

  if (canvasContext.measureText(text) <= maxWidth) {
    return text;
  }

  let multilineText = '';
  let multilineTextWidth = 0;

  for (const char of text) {
    const { width } = canvasContext.measureText(char);

    if (multilineTextWidth + width >= maxWidth) {
      multilineText += '\n';
      multilineTextWidth = 0;
    }

    multilineText += char;
    multilineTextWidth += width;
  }

  return multilineText;
}
```

**Comment by JoMartinezZhu** [comment]
> @chrisovu 使用下面的方法换行文本 :)
> 
> ```js
> const canvas = document.createElement('canvas');
> const canvasContext = canvas.getContext('2d');
> 
> export function optimizeMultilineText(text, font, maxWidth = 320) {
>   canvasContext.font = font;
> 
>   if (canvasContext.measureText(text) <= maxWidth) {
>     return text;
>   }
> 
>   let multilineText = '';
>   let multilineTextWidth = 0;
> 
>   for (const char of text) {
>     const { width } = canvasContext.measureText(char);
> 
>     if (multilineTextWidth + width >= maxWidth) {
>       multilineText += '\n';
>       multilineTextWidth = 0;
>     }
> 
>     multilineText += char;
>     multilineTextWidth += width;
>   }
> 
>   return multilineText;
> }
> ```

是在什么时候使用，会生效？？？
