### ISSUE TITLE
自定义image

### ISSUE THREAD

**Issue by liuqiyu** [gaoli/GGEditor#234]
## 这个功能解决了什么问题

自定义图片会出现边框

` Flow.registerNode('customNode', {
          draw(item){
            const group = item.getGraphicGroup()
            // const label = this.drawLabel(item)
            const keyShape = this.drawKeyShape(item);

            const model = item.getModel()
            console.log(model)
            group.addShape('image', {
              attrs: {
                img: model.image,
                x: -32,
                y: -32,
                width: 64,
                height: 64,
                zIndex: 9999
              }
            });

            // label && Util.toFront(label, group);
            return keyShape;
          }
        }, 'image')`

![image](https://user-images.githubusercontent.com/19789062/57821266-7c0b8000-77c2-11e9-9931-6f52fc07f42f.png)

## 你所期望的 API 是怎样的

请问如何设置只有图片 没有边框

**Comment by kzabc** [comment]
可以学习下吗   能看下你这的完整代码吗
@liuqiyu

**Comment by kzabc** [comment]
@liuqiyu  在吗

**Comment by zibu15** [comment]
这个貌似可以通过注释　this.drawKeyShape(item)来取消外边框
