### ISSUE TITLE
如何设置锚点样式 | How to style anchors?

### ISSUE THREAD

**Issue by veyorokon** [gaoli/GGEditor#245]
English: Is it possible to apply styles to anchors on a node? I would like a node with anchors that look like this:

中文: 是否可以将样式应用于节点上的锚点？我想要一个锚点看起来像这样的节点：

![AnchorStyle](https://user-images.githubusercontent.com/1963402/58356542-9b428700-7e2c-11e9-9d68-344500628500.png)

**Comment by veyorokon** [comment]
@gaoli

**Comment by Marckon** [comment]
this is a unique need,  and GGEditor does not support this kind of configuration. However, you can completely draw your own node referring to [G6](https://github.com/antvis/g6).  

I give you a very simple demo（`draw` function has been overridden):
- [demo 🔗](https://codesandbox.io/s/staging-dream-mm21wymnmx)

Well, you need to improve this demo with your specific demand.
