### ISSUE TITLE
有没有监听undo和redo的事件？

### ISSUE THREAD

**Issue by MengyanGuo** [gaoli/GGEditor#247]

**Comment by gaoli** [comment]
@MengyanGuo 可以监听以下两个事件：

```
onBeforeCommandExecute
onAfterCommandExecute
```

**Comment by MengyanGuo** [comment]
> @MengyanGuo 可以监听以下两个事件：
> 
> ```
> onBeforeCommandExecute
> onAfterCommandExecute
> ```

**好的，谢谢，我试下**
