### ISSUE TITLE
[Flow]请问如何定制anchor point位置？

### ISSUE THREAD

**Issue by BigYu** [gaoli/GGEditor#250]

**Comment by MengyanGuo** [comment]
流程图能改成拓扑图的锚点吗？

**Comment by veyorokon** [comment]
After the 'draw(item)' function for your custom node, add: 

```
 anchor(item){
            return [
                [0.5, 0 ], //Top
                [0.5, 0.5], //Center
                [0.5, 1], //Bottom
            ]
        }
```

Those arrays control the location of the anchor points. E.g: [ x, y ] and a value of 1 is the 'end' of the object along that axis. But you can add values greater or less than one to have anchors slightly outside of the object.

**Comment by BigYu** [comment]
@veyorokon 如果我想在在这里动态的给每一个节点设置锚点位置 是不可行的吗？
![image](https://user-images.githubusercontent.com/5934735/58604572-6a989c80-82c7-11e9-82f0-70e29b129333.png)
这样做好像没有用：
![image](https://user-images.githubusercontent.com/5934735/58604588-7ab07c00-82c7-11e9-8aa8-0d777643187f.png)

**Comment by BigYu** [comment]
实际上 我希望anchorPoints是根据后端的返回值计算得到的

**Comment by veyorokon** [comment]
Dynamic Anchor Points ||  动态锚点

English: You can try passing in anchor points as a prop
Chinese:  您可以尝试将锚点作为节点模型的属性传递

[demo](https://codesandbox.io/s/ggeditor-flow-dynamic-anchorpoints-d6xso?fontsize=14)
