### ISSUE TITLE
flow 中 edge 配置的size/lineWidth无效

### ISSUE THREAD

**Issue by fxq1997929** [gaoli/GGEditor#252]
source: data[i].id,
        target: data[i+1].id,
        sourceAnchor: 1,
        targetAnchor: 0,
        size: 25,
        lineWidth: 30,
例如这样设置边的属性，想实现线条粗细的变化，无法实现

**Comment by JustLikeU** [comment]
请问可以设置edge的颜色吗

**Comment by Linyccc** [comment]
> 请问可以设置edge的颜色吗

可以设置，自定义节点
![image](https://user-images.githubusercontent.com/38371796/88997221-bf97ce80-d321-11ea-8f79-12c7a8d3627d.png)
