### ISSUE TITLE
RegisterBehaviour没有任何反应

### ISSUE THREAD

**Issue by Xinaction** [gaoli/GGEditor#253]
RegisterBehaviour如何使用，文档没有描述，使用没有反应

**Comment by veyorokon** [comment]
English: 
There isn't much documentation for this. It took me a while to figure out too.

Chinese:
这方面没有太多文件。我花了一段时间才弄明白。

[Demo](https://codesandbox.io/s/ggeditor-flow-registernode-prik3?fontsize=14)

**Comment by Xinaction** [comment]
> **This is how you use RegisterBehaviour** || **这就是您使用RegisterBehaviour的方式**
> 
> English:
> There isn't much documentation for this. It took me a while to figure out too.
> 
> Chinese:
> 这方面没有太多文件。我花了一段时间才弄明白。
> 
> [Demo](https://codesandbox.io/s/ggeditor-flow-registernode-prik3?fontsize=14)

Thank you very very much for your help：）
