### ISSUE TITLE
RegisterCommand 自定义command

### ISSUE THREAD

**Issue by Xinaction** [gaoli/GGEditor#255]
RegisterCommand竟然只能自定义一个叫"customCommand"的命令，不能自定义name，也不能都叫"customCommand"，是我理解错了？
[Demo](https://codesandbox.io/s/ggeditor-registercommand-2gjdj)

应该如何自定义自己的键盘事件呢？

**Comment by veyorokon** [comment]
![image](https://user-images.githubusercontent.com/1963402/58739821-37d2cf00-83c1-11e9-96da-7152c9b4d4f5.png)

您必须将“dustomCommand：true”添加为Flow  - >快捷方式属性。

![image](https://user-images.githubusercontent.com/1963402/58739869-ac0d7280-83c1-11e9-84b5-13fd23c10825.png)

**Comment by Xinaction** [comment]
> ![image](https://user-images.githubusercontent.com/1963402/58739821-37d2cf00-83c1-11e9-96da-7152c9b4d4f5.png)
> 
> 您必须将“dustomCommand：true”添加为Flow - >快捷方式属性。
> 
> ![image](https://user-images.githubusercontent.com/1963402/58739869-ac0d7280-83c1-11e9-84b5-13fd23c10825.png)
> 
> 看到这里 [Demo](https://codesandbox.io/s/ggeditor-registercommand-d9ick?fontsize=14)

非常感谢你的帮助👍👍👍

**Comment by MrHuang123** [comment]
如何禁止Dlete快捷删除操作呢？

**Comment by MrHuang123** [comment]
选中节点，按delete键节点直接被删除了
