### ISSUE TITLE
可否根据容器大小画布自适应

### ISSUE THREAD

**Issue by cpa0701** [gaoli/GGEditor#261]
## 这个功能解决了什么问题
根据容器大小画布自适应，这样无论窗口改变或容器改变画布都能适应

**Comment by BigYu** [comment]
我用vh和vw来指定height和width可以

```jsx
<Flow style={{ height: "90vh", width: "60vw" }} />
```

**Comment by cpa0701** [comment]
> 我用vh和vw来指定height和width可以
> 
> ```js-jsx
> <Flow style={{ height: "90vh", width: "60vw" }} />
> ```

好的，我试试，谢谢

**Comment by cpa0701** [comment]
> > 我用vh和vw来指定height和width可以
> > ```
> > <Flow style={{ height: "90vh", width: "60vw" }} />
> > ```
> 
> 可以了，牛~谢谢
