### ISSUE TITLE
[Question] Programatically deselect

### ISSUE THREAD

**Issue by Kevin-K** [gaoli/GGEditor#282]
Is there anyway through the `propsAPI` to deselect the current selection?

**Use case:** 
1. I click on a node I open a form from my existing application in the `DetailPanel`.
2 When I press `submit` on that form, I update the node with the server response using the executeCommand/update functionality.
3. (Where I'm stuck) I then want to deselect the node.

**Comment by wxy1995** [comment]
```
const { editor } = propsAPI;
editor.getCurrentPage(). clearSelected();  // it will clear all selected items
```

**Comment by Kevin-K** [comment]
Thanks!
