### ISSUE TITLE
如何把koni组件中hover的小圆圈给关闭了

### ISSUE THREAD

**Issue by liaohongewi** [gaoli/GGEditor#299]
## 这个功能解决了什么问题
禁止copy事件/不能无限拷贝

**Comment by wxy1995** [comment]
试试这个呢
```
const config = {
  orbit: {
    satellite: [],
  },
}
<Koni {...config} />
```

**Comment by liaohongewi** [comment]
可以使用，非常感谢！

**Comment by qiumeihui** [comment]
> 试试这个呢
> 
> ```
> const config = {
>   orbit: {
>     satellite: [],
>   },
> }
> <Koni {...config} />
> ```

请问这个配置是在哪里看到的呢，源码里也没找到
