### ISSUE TITLE
npm start 是空白页啊？demo哪去了？

### ISSUE THREAD

**Issue by sowee121** [gaoli/GGEditor#58]
![image](https://user-images.githubusercontent.com/18671659/45430322-ba065080-b6d7-11e8-9eed-1300ccdc1e47.png)
![image](https://user-images.githubusercontent.com/18671659/45430391-d4d8c500-b6d7-11e8-8d82-6fbb02b8a9e0.png)

**Comment by gaoli** [comment]
流程图
http://localhost:8080/demo/#/flow

思维导图
http://localhost:8080/demo/#/mind

感谢反馈，我们在首页添加下相应链接：）
