### ISSUE TITLE
安装gg-editor使用流程图报错

### ISSUE THREAD

**Issue by nsuedu** [gaoli/GGEditor#63]
报错内容:index.js:2178 Warning: Failed child context type: Invalid child context `pageId` of type `string` supplied to `e`, expected `number`.

**Comment by topwood** [comment]
I have the same warning info, and the page is blank.

**Comment by nsuedu** [comment]
如果只像下面这样使用组件 Flow data 为空时是一片白的，
```
import GGEditor, { Flow } from 'gg-editor';

const data = {
  nodes: [],
  edges: [],
};

<GGEditor>
  <Flow data={data} />
</GGEditor>
```

2.  Mind 是有默认数据的：），你可以拿 Mind 试下

**Comment by nsuedu** [comment]
> I have the same warning info, and the page is blank.
  @@可以参考我上面的回复 @topwood

**Comment by gaoli** [comment]
@nsuedu `pageId` 类型报错是个警告，不会影响使用，下个版本修复：）
