### ISSUE TITLE
propsAPI为undefined的问题

### ISSUE THREAD

**Issue by nsuedu** [gaoli/GGEditor#67]
如下代码可以重现
```
import React from 'react';
import { withPropsAPI } from 'gg-editor';

class Component extends React.Component {
  componentDidMount() {
    const { propsAPI } = this.props;

    console.log(propsAPI);
  }
  render(){
    return <div>222</div>
  }
}

export default withPropsAPI(Component);
```

**Comment by nsuedu** [comment]
@gaoli @tennisonchan

**Comment by gaoli** [comment]
@nsuedu 使用的组件必需为 `GGEditor` 的子组件

**Comment by KaivOU** [comment]
![image](https://user-images.githubusercontent.com/36435545/57056546-d17d6280-6cd5-11e9-9407-138ca3781faa.png)
![image](https://user-images.githubusercontent.com/36435545/57056566-e823b980-6cd5-11e9-98bf-36e407730d3e.png)
