### ISSUE TITLE
执行build时报错

### ISSUE THREAD

**Issue by xuetaohe** [gaoli/GGEditor#69]
13 verbose stack Error: gg-editor@1.2.0 build: `NODE_ENV=production node --max_old_space_size=8192 ./node_modules/webpack/bin/webpack --config ./tools/webpack.config.prod.js --colors --profile --optimize-minimize`
13 verbose stack Exit status 1
13 verbose stack     **at EventEmitter.<anonymous>** (D:\Programs\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     **at emitTwo (events.js:126:13)**
13 verbose stack     **at EventEmitter.emit (events.js:214:7)**
13 verbose stack     **at ChildProcess.<anonymous>** (D:\Programs\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     **at emitTwo (events.js:126:13)**
13 verbose stack     **at ChildProcess.emit (events.js:214:7)**
13 verbose stack     **at maybeClose (internal/child_process.js:925:16)**
13 verbose stack     **at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)**
14 verbose pkgid gg-editor@1.2.0
15 verbose cwd D:\Projects\react\gg-editor
16 verbose Windows_NT 10.0.17134
17 verbose argv "D:\\Programs\\nodejs\\node.exe" "D:\\Programs\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build" "--scripts-prepend-node-path=auto"
18 verbose node v8.11.1
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error gg-editor@1.2.0 build: `NODE_ENV=production node --max_old_space_size=8192 ./node_modules/webpack/bin/webpack --config ./tools/webpack.config.prod.js --colors --profile --optimize-minimize`
22 error Exit status 1
23 error Failed at the gg-editor@1.2.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by gaoli** [comment]
@xuetaohe 为什么需要执行 `build` 命令？

**Comment by gaoli** [comment]
@xuetaohe 是 windows 系统？

**Comment by tennisonchan** [comment]
@xuetaohe 请问你改了什么？这个报错跟node/npm有关。你的node version 是什么？

**Comment by xuetaohe** [comment]
@gaoli 我其实是尝试性的修改，想尝试添加一些自己需要的功能，比如：查看和保存流程图数据的功能。
**我的npm版本：6.4.1**  （windows系统）

**Comment by xuetaohe** [comment]
@tennisonchan 我尝试加了点自己个性化的东西，就是尝试
我的node version是v8.11.1，
我的npm verison是6.4.1

**Comment by gaoli** [comment]
@xuetaohe 

我们无法重现你的构建问题 Orz ...

读取保存数据可以通过参照 [Props API](http://ggeditor.com/docs/api/propsAPI.zh-CN.html)，有其它的功能需求也可以提 [Issues](https://github.com/gaoli/GGEditor/issues)
