### ISSUE TITLE
请问如何能够屏蔽掉 Mind 节点上的双击事件？

### ISSUE THREAD

**Issue by yoonge** [gaoli/GGEditor#70]
我在 Mind Demo 的基础上作了少量修改，以便我在 NodePanel  区域可以同时修改文本和文本颜色，这导致我双击 Mind 节点进入编辑状态时，节点读取到的是一个 `[object Object]`，无法正常展示节点文本，部分代码如下：

``` javascript
// NodeDetail.js
// ...

let { label } = item.getModel();
if (typeof label === 'string') {
  label = {
    text: label,
    fill: '#333',
  };
}

// ...
```

``` javascript
// mind.js
export default {
  roots: [
    {
      label: {
        text: '根节点',
        fill: 'red',
      },
      children: [
        // ...
      ],
    },
  ],
};
```

我有尝试重写 graph 上监听的双击事件，但并不能覆盖默认的编辑事件
那么，我想请教有没有办法简单粗暴的屏蔽掉 Mind 节点上的双击编辑事件，保留单击选中，只让在右侧 NodePanel 区域编辑呢？
或者另一种方案：是否可以考虑让节点能够解析部分 html 标签以及样式呢？类似 Flow 的自定义图项？
以上，谢谢！

**Comment by gaoli** [comment]
@yoonge 

> 其实是有尝试添加同级字段，如 color、fill、style等，同样是参考的节点数据模型，但都不能正常读取生效，您的意思是自定义属性，需要自行处理？

自定义的属性，还需自行处理：）

**Comment by yoonge** [comment]
好的，我明白了，感谢您的回答 🙏

**Comment by JoMartinezZhu** [comment]
> 好的，我明白了，感谢您的回答 🙏

不明白，怎么自行处理？

**Comment by kitian616** [comment]
> 首先不建议改变 `label` 类型，其它地方也会用到这个字段。
> 
> 你完全可以添加一个与 `label` 同级的字段来保存填充颜色。
> 
> 如果仅仅想屏蔽掉双击编辑事件，最简单的方法是复写 `dblclickItemEditLabel` 行为，例如：
> 
> ```js-jsx
> <RegisterBehaviour name="dblclickItemEditLabel" behaviour={() => {}} />
> ```
> 
> 不管是 `Flow` 还是 `Mind` 现在都是支持自定义节点的，具体参照[这里](http://ggeditor.com/docs/api/registerNode.en-US.html)。
> 
> 还有个好消息，接下来的版本 G6-Editor 即将支持 SVG 渲染引擎，使用 HTML 定义结点将成为可能：）

"dblclickItemEditLabel" 是从哪里来的呢？是 G6 里的还是 GGEditor 中的？没查找到相应的资料，同时源码里也搜索不到
