### ISSUE TITLE
如果要显示tooltip,最好的办法是什么呢?

### ISSUE THREAD

**Issue by Yeung2017** [gaoli/GGEditor#79]
## 需求描述
鼠标移入Item时,显示该Item的详细信息,移出则隐藏详细信息.
## 遇到的问题
1.没有内置Tooltip组件
2.想使用自定义交互进行处理,又遇到了 #78 的问题
所以就暂时卡住了

**Comment by gaoli** [comment]
以下是我项目中的实现方案，供你参考：

1. 使用 `onNodeMouseEnter` 和 `onNodeMouseLeave` 监听鼠标移入移出 Node
2. 使用 [getDomPoint](https://www.yuque.com/antv/g6/api-graph#2pn6kw) 方法获取结点对应 DOM 坐标
3. 绘制相应浮动，如果项目基于 antd 的话可以直接使用 [Popover](https://ant-design.gitee.io/components/popover-cn/)

**Comment by Yeung2017** [comment]
@gaoli 
谢谢提示

**Comment by nsuedu** [comment]
请教下 getDomPoint 方法的graph对象是从 ggEditor里面的 哪里获取呢? 
还有是通过ggEditor的什么属性绘制浮动呢， 还是使用原生canvas绘制? @gaoli @Yeung2017 @

**Comment by limingzhe** [comment]
@nsuedu 有同样的问题，请问你是怎么解决了呢

**Comment by JoMartinezZhu** [comment]
> 以下是我项目中的实现方案，供你参考：
> 
> 1. 使用 `onNodeMouseEnter` 和 `onNodeMouseLeave` 监听鼠标移入移出 Node
> 2. 使用 [getDomPoint](https://www.yuque.com/antv/g6/api-graph#2pn6kw) 方法获取结点对应 DOM 坐标
> 3. 绘制相应浮动，如果项目基于 antd 的话可以直接使用 [Popover](https://ant-design.gitee.io/components/popover-cn/)

怎么去绘制浮动？？？

**Comment by anjamirth** [comment]
@eevin, @JoMartinezZhu @nsuedu @limingzhe 

> The following is the implementation scheme in my project for your reference:
> 
> 1. Use `onNodeMouseEnter`and `onNodeMouseLeave`monitor the mouse moved out of the Node
> 2. Use the [getDomPoint](https://www.yuque.com/antv/g6/api-graph#2pn6kw) method to get the DOM coordinates of the node
> 3. Draw the corresponding float, if the project is based on antd, you can use [Popover](https://ant-design.gitee.io/components/popover-cn/) directly[](https://ant-design.gitee.io/components/popover-cn/)

How to draw the floats or Popover. I am also using antd pro-blocks. I am new to this.
Were you able to solve this? Can you pls guide me.
