### ISSUE TITLE
关于点击item，NodeDetail  props中获取不到 getSelected, updateItem报错，求帮忙看看啥问题

### ISSUE THREAD

**Issue by flg717** [gaoli/GGEditor#80]
我按照demo写了一下，其他都没问题，也可以直接显示出来内容，但是点击选中流程图中的一个节点，或者线的时候，报错。。。。
***代码如果
![image](https://user-images.githubusercontent.com/19221801/46875120-7422e080-ce6d-11e8-933c-0a5d6fad599f.png)
![image](https://user-images.githubusercontent.com/19221801/46875152-8270fc80-ce6d-11e8-8e3a-67062faff0e5.png)

***报错如图
![image](https://user-images.githubusercontent.com/19221801/46875070-52c1f480-ce6d-11e8-816e-4a499fffef5b.png)
 const { form, getSelected, updateItem } = this.props;
感觉像是哪儿没重写， NodeDetail  props中获取不到 getSelected, updateItem ，只有form。。。感谢回复

**Comment by gaoli** [comment]
```jsx
handleSubmit = () => {
  const { form, propsAPI } = this.props;
  const { getSelected, update } = propsAPI;

  form.validateFieldsAndScroll((err, values) => {
    if (err) {
      return;
    }

    const item = getSelected()[0];

    if (!item) {
      return;
    }

    update(item, {
      ...values,
    });
  });
}
```

@flg717 亲，使用方式改变喽，可以参考 [文档](http://ggeditor.com/docs/api/propsAPI.zh-CN.html)
