### ISSUE TITLE
如何阻止添加node？

### ISSUE THREAD

**Issue by kewanglantian** [gaoli/GGEditor#84]
比如我要判断只能添加一次开始节点，添加第二次时就不让他添加成功怎么办？

**Comment by kewanglantian** [comment]
可行，谢谢

**Comment by escapiststupor** [comment]
@gaoli  高大哥，想请问如何在onAfterCommandExecute「直接将其移除」，据我所知Editor 是一个uncontrolled component，只能接收初始时的数据，一旦instance被建立以后，除非强制Editor重新渲染，否则如何能在onAfterCommandExecute 里面直接移除一个node？有任何暴露出的API吗？
