### ISSUE TITLE
如何禁止对流程图的操作，只能看，不能移动？

### ISSUE THREAD

**Issue by kewanglantian** [gaoli/GGEditor#89]
比如禁止节点拖动，禁止线更改目标点

**Comment by gaoli** [comment]
可以设置 `mode` 参数为 `readOnly`，但要特别注意：只读场景下不允许再加载其它组件，例如：`ItemPanel`

```jsx
<GGEditor>
  <Flow graph={{ mode: 'readOnly' }} />
</GGEditor>
```

**Comment by kewanglantian** [comment]
可以了，谢谢

**Comment by JoMartinezZhu** [comment]
> 可以设置 `mode` 参数为 `readOnly`，但要特别注意：只读场景下不允许再加载其它组件，例如：`ItemPanel`
> 
> ```js-jsx
> <GGEditor>
>   <Flow graph={{ mode: 'readOnly' }} />
> </GGEditor>
> ```

类似，这些配置 在文档上并没有看到相关说明

**Comment by xwjune** [comment]
设置readOnly,不能点击查看节点属性了  @gaoli @kewanglantian @JoMartinezZhu @tennisonchan @lzcers
