### ISSUE TITLE
关于 onNodeDrop  和 onNodeDragEnd  触发的机制，是否是 BUG ？

### ISSUE THREAD

**Issue by yoonge** [gaoli/GGEditor#93]
## 问题描述:
我想实现的效果——不允许将某类型的节点拖动到另一特定类型的节点后面：通过拖动完成获取新的父节点类型来决定是否撤销此次拖动操作。
具体请看下面动图演示，拖动了三次，只有第二次光标在 placeholder 上释放时才能触发 onNodeDrop，并正确获取到新的父节点；
也尝试过使用 onNodeDragEnd，虽然此事件无论光标在哪儿释放都能触发，但只有在 placeholder 上释放才能正确获取到新的父节点（只要光标在 placeholder  附近释放都能拖动成功）

## 问题截图:
![-2018-10-29-10 41 53](https://user-images.githubusercontent.com/8704741/47627362-85a50180-db6a-11e8-896a-7baf1115a57c.gif)

## 理想的状态是:
只要拖动成功，每次都触发 onNodeDrop （不论光标在哪儿释放）

## 次理想的状态:
光标只要不是在 placeholder 上释放，都拖动失败

## 相关代码
``` javascript
<Mind
    data={xmindData}
    className={styles.xmind}
    graph={{ fitView: 'cc' }}
    onNodeDrop={e => {
        const { propsAPI } = this.props;
        console.log('触发了 onNodeDrop: ', e);
        const parent = e && e.item && e.item.getParent();
        const parentModel = parent && parent.getModel();
        console.log('获取到的 parentModel: ', parentModel);
        if (parentModel && parentModel.type === 'jump') {
            propsAPI.executeCommand('undo');
            message.error('禁止该操作！');
        }
    }}
/>
```

**Comment by gaoli** [comment]
@yoonge 换个思路，监听 onAfterChange 事件

```jsx
onAfterChange={(e) => {
  const { action, item } = e;

  const model = item.getModel();

  if (action !== 'add' || model.isPlaceholder) {
    return;
  }

  const parent = item.getParent();
  const parentModel = parent.getModel();

  console.log('parentModel: ', parentModel);
}}
```

**Comment by gaoli** [comment]
@yoonge 还有个概念需要明确下：在 `drag` 事件中 `item` 是拖拽时命中的图项（就是你第二次拖拽的情况），`currentItem` 是开始拖拽时命中的图项。

**Comment by yoonge** [comment]
感谢回复！

尝试了您说的 `onAfterChange` 确实可以实现我想要的效果，同时还省去了执行 `appendChild` 命令时
的一段判断 😂 还是自己不够仔细，忽略了这个事件

至于您说的 `drag` 事件中的 `item`  和 `currentItem` 我想我是理解的，正因为如此， 才一直纠结 `onNodeDragEnd` 时获取到的 `item` 为啥经常是 `null` 😬

再次感谢提供这么好的项目 🙏🏻
