### ISSUE TITLE
文档感觉不是很全呢？朋友！是要结合g6的一起看吗？

### ISSUE THREAD

**Issue by ouaisheinie** [gaoli/GGEditor#96]
比如说 DetailPanel 里面 怎么打印值的方法  
也可能是我刚接触 没怎么看的原因。哈哈 挺好的。

**Comment by gaoli** [comment]
@ouaisheinie 

现有的文档应该是能满足一般的开发需求的，你所说的打印值具体是指什么？

如果是一些方法的调用，你可能需要 [Props API](http://ggeditor.com/docs/api/propsAPI.zh-CN.html)

**Comment by gaoli** [comment]
@ouaisheinie 

使用 `withPropsAPI` 包装你要使用 API 的 React 组件（这里要注意，该组件必须为 `GGEditor` 的子组件，不然无法获取），如果要获取当前的数据，你需要调用的方法是 `save()`

**Comment by ouaisheinie** [comment]
> @ouaisheinie
> 
> 使用 `withPropsAPI` 包装你要使用 API 的 React 组件（这里要注意，该组件必须为 `GGEditor` 的子组件，不然无法获取），如果要获取当前的数据，你需要调用的方法是 `save()`

谢谢高兄弟  很详细的解释  已经没问题了  谢谢
